Created TextLinks to replace DisplayLinks and added to announcements
stuysu/epsilon pull request #246
Opened 2024-10-14 01:20 UTC by SnowyNate

TextLinks component has been created to replace the previous function DisplayLinks, which did not support newlines. TextLinks functionality has been added to announcements in Catalog page and AlertDisplay. Fixes issue #233

2024-11-29 01:53 UTC, TheEgghead27 requested changes
This is amazing! I am so sorry I lost track of this PR

I suppose this component should also be used for the socials section of clubs?

2024-11-29 01:53 UTC, TheEgghead27 commented on src/comps/ui/AlertDisplay.tsx
> +import TextLinks from "./TextLinks";
I suppose you could have simply kept the component called DisplayLinks to reduce the number of breaking changes, but this is fine

2024-11-29 01:53 UTC, TheEgghead27 commented on src/comps/ui/TextLinks.tsx
> +                            <a
It would be best to use a MUI Link (or other styled link) for UI consistency

2024-12-21 05:28 UTC, SnowyNate commented
Updated to PR #262

2024-12-21 05:28 UTC, closed without merging