UI updates to the unauthenticated login page
stuysu/epsilon pull request #247
Opened 2024-10-14 15:36 UTC by willpill

2024-10-14 22:01 UTC, SnowyNate requested changes
See comment

2024-10-14 22:01 UTC, SnowyNate commented on src/index.css
Only thing I'm worried about here is what it'll do to the rest of the text throughout the website- maybe we should keep Roboto Condensed FOR NOW in there just in case?

2024-10-15 15:48 UTC, willpill commented on src/index.css
Will fix fonts for paragraphs.

2024-10-16 22:04 UTC, merged

2024-10-20 23:17 UTC, SnowyNate commented
Rohan informed me of a good point that we should add the Catalog button back due to reasons such as pre-freshies without accounts during open house trying to explore the new system and get used to it. We could have a little divider beneath the google sign in button maybe and change it to "Browse as guest"